ArtWorkManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
    url(r'^developer/', include('developer.urls', namespace='developer')),
    url(r'^art/', include('art.urls', namespace='art')),
    url(r'^plan/', include('plan.urls', namespace='plan')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

art/urls.py
from django.conf.urls import patterns, include, url
from art import views

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='art'),

    url(r'^audit/$', views.ArtAuditView.as_view(), name='audit'),

    url(r'^upload/$', views.UploadTaskView.as_view(), name='upload'),

    url(r'^up_upload/$', views.UpdateUploadTaskView.as_view(), name='up_upload'),

    url(r'^pass/$', views.ArtPassView.as_view(), name='pass'),

    url(r'^faild/$', views.ArtFaildView.as_view(), name='faild'),

    url(r'^resource_upload/$', views.upload, name='resource_upload'),

    url(r'^update/$', views.update, name='update'),

]

login/urls.py
from django.conf.urls import patterns, include, url
from login import views

urlpatterns = [
    # ex: /sign_in/
    url(r'^sign_in/$', views.sign_in, name='sign_in'),

    # ex: /sign_out/
    url(r'^sign_out/$', views.sign_out, name='sign_out'),

    # ex: /sign_success/
    url(r'^menu/$', views.MenuViews.as_view(), name='menu'),
]

art/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

art/views.py
#coding=utf8

from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from home.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import os
import re


def is_sign_in(request):
    if not request.user.is_authenticated():
        return ('/?next=%s' % request.path)
    else:
        if request.user.has_perm('home.can_art'):
            return
        else:
            return ('/login/menu/')

def pagination(request, number, target):

    paginator = Paginator(target, number)
    page = request.GET.get('page')
    try:
        target = paginator.page(page)
    except PageNotAnInteger:
        target = paginator.page(1)
    except EmptyPage:
        target = paginator.page(paginator.num_pages)

    return (target)


def art_count(request):

    user_id = request.user.id

    dart_list = list(Art.objects.filter(user=user_id, screen_shot="", resource_file=""))
    if dart_list:
        ddsc = len(dart_list)
        darts = pagination(request, 10, dart_list)
    else:
        ddsc = 0
        darts = []

    sarts = list(Art.objects.filter(user=user_id, is_audit=0))
    if sarts:
        ddsh = int(len(sarts)) - int(ddsc)
    else:
        ddsh = 0
        sarts = []

    s_list = []
    for p in sarts:
        if p not in darts:
            s_list.append(p)

    if s_list:
        sart_list = pagination(request, 10, s_list)
    else:
        sart_list = []


    part_list = list(Art.objects.filter(user=user_id, is_audit=1, is_pass=1))
    if part_list:
        psh = len(part_list)
        parts = pagination(request, 10, part_list)
    else:
        psh = 0
        parts = []

    fart_list = list(Art.objects.filter(user=user_id, is_audit=1, is_pass=0))
    if fart_list:
        fsh = len(fart_list)
        farts = pagination(request, 10, fart_list)
    else:
        fsh = 0
        farts = []

    context = {
        "darts": darts, # 未提交的总资源
        "ddsc": ddsc, # 未提交的总资源的个数
        "sart_list": sart_list, # 待审核的资源
        "ddsh": ddsh, # 待审核资源的个数
        "parts": parts, # 通过的资源
        "psh": psh, # 通过资源的个数
        "farts": farts, # 未通过的资源
        "fsh": fsh, # 未通过资源的个数
    }

    return (context)


class IndexView(generic.View):
    templates_file = 'ArtIndex.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        context = art_count(request)

        return render(request,
                      self.templates_file,
                      context)


class ArtAuditView(generic.View):
    templates_file = 'ArtAudit.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        context = art_count(request)

        return render(request,
                      self.templates_file,
                      context)


class ArtPassView(generic.View):
    templates_file = 'ArtPass.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        context = art_count(request)

        return render(request,
                      self.templates_file,
                      context)


class ArtFaildView(generic.View):
    templates_file = 'ArtFaild.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        context = art_count(request)

        return render(request,
                      self.templates_file,
                      context)


class UploadTaskView(generic.View):
    templates_file = 'ArtUpload.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        if 'art_id' in request.GET and request.GET['art_id']:
            art_id = request.GET['art_id']
        else:
            return HttpResponse("Art ID错误!")

        arts = list(Art.objects.filter(id=int(art_id)))
        if arts:
            art_list = []
            for p in arts:
                artinfos = list(ArtInfo.objects.filter(art=p.id))
                if artinfos:
                    artinfo_list = []
                    for q in artinfos:
                        tag_name = list(GroupToTag.objects.filter(id=q.tag.id))
                        art_info = {"name": tag_name.pop().info, "value": q.value}
                        artinfo_list.append(art_info)
                else:
                    artinfo_list = []
                a = {"id": p.id, "format": p.group.format, "group": p.group.name, "big_version": p.version, "description": p.description, 'art_info': artinfo_list}
                art_list.append(a)
        else:
            art_list = []

        context = {
            "art_list": art_list, # 资源信息
            "art_id": art_id, # 资源ID
        }

        return render(request,
                      self.templates_file,
                      context)


class UpdateUploadTaskView(generic.View):
    templates_file = 'ArtUpdateUpload.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        if 'art_id' in request.GET and request.GET['art_id']:
            art_id = request.GET['art_id']
        else:
            return HttpResponse("Art ID错误!")

        arts = list(Art.objects.filter(id=int(art_id)))
        if arts:
            art_list = []
            for p in arts:
                artinfos = list(ArtInfo.objects.filter(art=p.id))
                if artinfos:
                    artinfo_list = []
                    for q in artinfos:
                        tag_name = list(GroupToTag.objects.filter(id=q.tag.id))
                        art_info = {"name": tag_name.pop().info, "value": q.value}
                        artinfo_list.append(art_info)
                else:
                    artinfo_list = []
                a = {"id": p.id, "format": p.group.format, "group": p.group.name, "big_version": p.version, "reason": p.reason, 'art_info': artinfo_list}
                art_list.append(a)
        else:
            art_list = []

        context = {
            "art_list": art_list,
            "art_id": art_id,
        }

        return render(request,
                      self.templates_file,
                      context)


def upload(request):

    if "art_id" in request.POST and request.POST['art_id']:
        art_id = request.POST['art_id']
    else:
        return HttpResponse("Art ID不存在!")

    if "big_version" in request.POST and request.POST['big_version']:
        big_version = request.POST['big_version']
    else:
        return HttpResponse("Big_version 不存在!")

    if "preview" in request.FILES and request.FILES['preview']:
        screen_shot = request.FILES['preview']
    else:
        return HttpResponse("截图不存在!")

    if "resource" in request.FILES and request.FILES['resource']:
        resource = request.FILES['resource']
    else:
        return HttpResponse("资源不存在!")

    arts = list(Art.objects.filter(id=int(art_id)))
    if not arts:
        return HttpResponse("Art不存在!")

    # version

    art_list = []

    id_by_group = []
    for p in arts:
        groups = list(Art.objects.filter(group=p.group.id))
        for q in groups:
            id_by_group.append(q.id)
    art_list.append(id_by_group)

    artinfos = list(ArtInfo.objects.filter(art=int(art_id)))
    for p in artinfos:
        tags = list(ArtInfo.objects.filter(tag=p.tag.id, value=p.value))
        if tags:
            id_by_tag = []
            for q in tags:
                id_by_tag.append(q.art.id)
        else:
            id_by_tag = []
        art_list.append(id_by_tag)

    x = art_list.pop()
    for p in art_list:
        if x != p:
            y = []
            for q in x:
                if q in p:
                    y.append(q)
            x = y

    if not art_list:
        version = big_version + ".0"
    else:
        version_list = []
        for m in x:
            art_version = list(Art.objects.filter(id=m))
            versions = art_version.pop().version
            version_list.append(versions)

        version_info = []
        for p in version_list:
            it = re.finditer(r"\d+", p)
            num = []
            for match in it:
                b = match.group()
                num.append(b)
            if num[0] == big_version:
                version_info.append(p)

        if version_info:
            max_v = max(version_info)
            if max_v == big_version:
                version = str(num[0]) + "." + str(0)
            else:
                it = re.finditer(r"\d+", max_v)
                num = []
                for match in it:
                    a = match.group()
                    num.append(a)

                small_v = int(num[1]) + 1
                version = str(num[0]) + "." + str(small_v)
        else:
            version = big_version + ".0"

    for p in arts:

        # Determine upload file type
        format_type = p.group.format
        formal_type = os.path.splitext(resource.name)[1].lower()
        if not formal_type in (format_type):
            return HttpResponse('资源格式错误!')

        p.version = version
        p.screen_shot = screen_shot
        p.resource_file = resource
        p.save()

    return HttpResponseRedirect('/art/audit/')


def update(request):

    if "art_id" in request.POST and request.POST['art_id']:
        art_id = request.POST['art_id']
    else:
        return HttpResponse("Art ID不存在!")

    if "preview" in request.FILES and request.FILES['preview']:
        screen_shot = request.FILES['preview']
    else:
        return HttpResponse("截图不存在!")

    if "resource" in request.FILES and request.FILES['resource']:
        resource = request.FILES['resource']
    else:

art/templates/ArtAudit.html
{% extends 'ArtBase.html' %}
{% block content %}

    <h3>等待审核任务</h3>
    <table class="table" id="audit" style="margin-top: 20px;">
        <thead style="font-size: 14px; font-weight: 800;">
            <tr></tr>
            <tr>
                <td>ID</td>
                <td>类别</td>
                <td>预览图</td>
                <td>任务描述</td>
            </tr>
        </thead>
        <tbody>
            {% if not sart_list %}
                <tr>
                    <td colspan="4">没有待审核任务!</td>
                </tr>
            {% else %}
                {% for p in sart_list %}
                    <tr>
                        <td>{{ p.id }}</td>
                        <td>{{ p.group.name }}</td>
                        <td>
                            <script>
                                $(function() {
                                    $('#gallery{{ p.id }}').poptrox({
                                        usePopupCaption: true
                                    });
                                });
                            </script>
                            <div id="gallery{{ p.id }}">
                                <a href="{{ MEDIA_URL }}{{ p.screen_shot }}">
                                    <img width="150px" src="{{ MEDIA_URL }}{{ p.screen_shot }}" />
                                </a>
                            </div>
                        </td>
                        <td>
                            <textarea class="form-control" disabled>{{ p.description }}</textarea>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>

    {% if sart_list and sart_list.paginator.num_pages != 1 %}
        <nav style="text-align: center;">
            <ul class="pagination">
                <li>
                    <a href="/art/audit/?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li>
                    {% if sart_list.has_previous %}
                        <a href="/art/audit/?page={{ sart_list.previous_page_number }}" aria-label="Previous">上一页</a>
                    {% else %}
                        <a href="/art/audit/?page={{ sart_list.number }}" aria-label="Previous">上一页</a>
                    {% endif %}
                </li>
                {% for p in sart_list.paginator.page_range %}
                    <li {% if sart_list.number == p %}class="active"{% endif %}><a href="/art/audit/?page={{ p }}">{{ p }}</a></li>
                {% endfor %}
                <li>
                    {% if sart_list.has_next %}
                        <a href="/art/audit/?page={{ sart_list.next_page_number }}" aria-label="Previous">下一页</a>
                    {% else %}
                        <a href="/art/audit/?page={{ sart_list.number }}" aria-label="Previous">下一页</a>
                    {% endif %}
                </li>
                <li>
                    <a href="/art/audit/?page={{ sart_list.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}

{% endblock %}

art/templates/ArtBase.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>ArtWorkManager | 提交资源</title>
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'ArtWorkManager/css/main.css' %}" >
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="{% static 'ArtWorkManager/js/main.js' %}"></script>
    <script src="{% static 'ArtWorkManager/js/jquery.poptrox.js' %}"></script>
</head>
<body>
    <div class="menus">
        <div class="row">
            <div class="col-xs-7">
                <a href="/login/menu/">
                    <h3>ArtWorkManager <small>美术资源管理系统</small></h3>
                </a>
            </div>
            <div class="col-xs-5">
                <h2 id="username">
                    <span class="glyphicon glyphicon-user"></span>{{ user.username }}　
                    <span class="glyphicon glyphicon-share-alt"></span>
                    <a href="{% url 'login:sign_out' %}">退出</a>
                </h2>
            </div>
        </div>
    </div>

    <div class="art">
        <div class="row">
            <div class="col-xs-3">
                <a href="/login/menu/" style="color: #000000;"><h2>资源管理</h2></a>
                <div class="row">
                    <div class="col-xs-12" style="margin-top: 20px;">
                        <a href="/art/">
                            <div class="admin_task">
                                <div class="dsh"></div>
                                <div class="task_font">等待上传</div>
                                <div class="task_num">{{ ddsc }}</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-xs-12" style="margin-top: 20px;">
                        <a href="/art/audit/">
                            <div class="admin_task">
                                <div class="dsh" style="background: #337ab7;"></div>
                                <div class="task_font">等待审核</div>
                                <div class="task_num">{{ ddsh }}</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-xs-12" style="margin-top: 20px;">
                        <a href="/art/pass/">
                            <div class="admin_task">
                                <span class="glyphicon glyphicon-ok-circle" style="color: green; font-size: 30px;"></span>
                                <div class="task_font">审核通过</div>
                                <div class="task_num">{{ psh }}</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-xs-12" style="margin-top: 20px; margin-bottom: 20px;">
                        <a href="/art/faild/">
                            <div class="admin_task">
                                <span class="glyphicon glyphicon-remove-circle" style="color: red; font-size: 30px;"></span>
                                <div class="task_font">审核未通过</div>
                                <div class="task_num">{{ fsh }}</div>
                            </div>
                        </a>
                    </div>
                </div>
                <a href="/login/menu"><div id="back">返回主页</div></a>
            </div>
            <div class="col-xs-9">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

</div>
</body>
</html>

art/templates/ArtFaild.html
{% extends 'ArtBase.html' %}
{% block content %}

    <h3>审核未通过资源</h3>
    <table class="table" id="audit" style="margin-top: 20px;">
        <thead style="font-size: 14px; font-weight: 800;">
            <tr></tr>
            <tr>
                <td>ID</td>
                <td>类别</td>
                <td>预览图</td>
                <td>审核意见</td>
                <td>修改</td>
            </tr>
        </thead>
        <tbody>
            {% if not farts %}
                <tr>
                    <td colspan="5">没有审核未通过资源!</td>
                </tr>
            {% else %}
                {% for p in farts %}
                    <tr>
                        <td>{{ p.id }}</td>
                        <td>{{ p.group.name }}</td>
                        <td>
                            <script>
                                $(function() {
                                    $('#gallery{{ p.id }}').poptrox({
                                        usePopupCaption: true
                                    });
                                });
                            </script>
                            <div id="gallery{{ p.id }}">
                                <a href="{{ MEDIA_URL }}{{ p.screen_shot }}">
                                    <img width="150px" src="{{ MEDIA_URL }}{{ p.screen_shot }}" />
                                </a>
                            </div>
                        </td>
                        <td>
                            <textarea class="form-control" disabled>{{ p.reason }}</textarea>
                        </td>
                        <td>
                            <a href="javascript:AjaxGet('/art/up_upload/?art_id={{ p.id }}')">
                                <button class="btn btn-primary btn-block btn-sm" style="width: 100%;">修改</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>

    {% if farts and farts.paginator.num_pages != 1 %}
        <nav style="text-align: center;">
            <ul class="pagination">
                <li>
                    <a href="/art/faild/?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li>
                    {% if farts.has_previous %}
                        <a href="/art/faild/?page={{ farts.previous_page_number }}" aria-label="Previous">上一页</a>
                    {% else %}
                        <a href="/art/faild/?page={{ farts.number }}" aria-label="Previous">上一页</a>
                    {% endif %}
                </li>
                {% for p in farts.paginator.page_range %}
                    <li {% if farts.number == p %}class="active"{% endif %}><a href="/art/faild/?page={{ p }}">{{ p }}</a></li>
                {% endfor %}
                <li>
                    {% if farts.has_next %}
                        <a href="/art/faild/?page={{ farts.next_page_number }}" aria-label="Previous">下一页</a>
                    {% else %}
                        <a href="/art/faild/?page={{ farts.number }}" aria-label="Previous">下一页</a>
                    {% endif %}
                </li>
                <li>
                    <a href="/art/faild/?page={{ farts.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}

    <div id="popDiv" class="mydiv" style="display:none;"></div>
    <div id="bg" class="bg" style="display:none;"></div>
    <iframe id='popIframe' class='popIframe' frameborder='0'></iframe>

{% endblock %}

art/templates/ArtIndex.html
{% extends 'ArtBase.html' %}
{% block content %}

    <h3>等待上传资源任务</h3>
    <table class="table" id="audit" style="margin-top: 20px;">
        <thead style="font-size: 14px; font-weight: 800;">
            <tr></tr>
            <tr>
                <td>ID</td>
                <td>类别</td>
                <td>任务优先级</td>
                <td>任务描述</td>
                <td>上传资源</td>
            </tr>
        </thead>
        <tbody>
            {% if not darts %}
                <tr>
                    <td colspan="5">没有等待上传资源的任务!</td>
                </tr>
            {% else %}
                {% for p in darts %}
                    <tr>
                        <td>{{ p.id }}</td>
                        <td>{{ p.group.name }}</td>
                        <td>{{ p.priority }}</td>
                        <td>
                            <textarea class="form-control" disabled>{{ p.description }}</textarea>
                        </td>
                        <td>
                            <a href="javascript:AjaxGet('/art/upload/?art_id={{ p.id }}')">
                                <button class="btn btn-primary btn-block btn-sm" style="width: 100%;">上传</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>

    <div id="popDiv" class="mydiv" style="display:none;"></div>
    <div id="bg" class="bg" style="display:none;"></div>
    <iframe id='popIframe' class='popIframe' frameborder='0'></iframe>

    {% if darts and darts.paginator.num_pages != 1 %}
        <nav style="text-align: center;">
            <ul class="pagination">
                <li>
                    <a href="/art/?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li>
                    {% if darts.has_previous %}
                        <a href="/art/?page={{ darts.previous_page_number }}" aria-label="Previous">上一页</a>
                    {% else %}
                        <a href="/art/?page={{ darts.number }}" aria-label="Previous">上一页</a>
                    {% endif %}
                </li>
                {% for p in darts.paginator.page_range %}
                    <li {% if darts.number == p %}class="active"{% endif %}><a href="/art/?page={{ p }}">{{ p }}</a></li>
                {% endfor %}
                <li>
                    {% if darts.has_next %}
                        <a href="/art/?page={{ darts.next_page_number }}" aria-label="Previous">下一页</a>
                    {% else %}
                        <a href="/art/?page={{ darts.number }}" aria-label="Previous">下一页</a>
                    {% endif %}
                </li>
                <li>
                    <a href="/art/?page={{ darts.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}

{% endblock %}

art/templates/ArtUpdateUpload.html
<div id="wall" style="width: 700px; height: 500px;">

    <div class="row" style="padding: 20px;">
        <div class="col-xs-8">
            <h3 style="margin: 0;">修改资源</h3>
        </div>
        <div class="col-xs-4" style="text-align: center;">
            <a href="javascript:closeDiv();">
                <div style="width: 26px; height: 26px; line-height: 28px; background: #337ab7; color: #ffffff; float: right;">
                    <span class="glyphicon glyphicon-remove"></span>
                </div>
            </a>
        </div>
    </div>

    <div style="width: 100%; height: 2px; background: #337ab7;"></div>

    {% for p in art_list %}
        <div class="artinfos" style="margin-top: 20px;">
            <div class="col-xs-6">
                <h4>审核意见</h4>
                <textarea class="form-control" style="height: 250px; resize: none;" disabled>{{ p.reason }}</textarea>
            </div>
            <div class="col-xs-6">
                <h4>任务信息</h4>
                <div id="pic_info">
                    <div class="col-xs-5">类别</div>
                    <div class="col-xs-7">{{ p.group }}</div>
                </div>
                {% for q in p.art_info %}
                    <div id="pic_info">
                        <div class="col-xs-5">{{ q.name }}</div>
                        <div class="col-xs-7">{{ q.value }}</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    <form action="{% url 'art:update' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="uploads">
            <div class="col-xs-4">
                <div class="form-group">
                    <label for="priority">资源截图</label>
                    <input type="file" class="form-control input-sm" name="preview">
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group">
                    <label for="priority">资源原文件</label>
                    <input type="file" class="form-control input-sm" name="resource">
                </div>
            </div>
            <input type="hidden" name="art_id" value="{{ art_id }}">
            <div class="col-xs-2">
                <button class="btn btn-primary btn-block btn-sm" style="width: 100%;">上传</button>
            </div>
            <div class="col-xs-2">
                <a href="javascript:closeDiv();">
                    <button class="btn btn-primary btn-block btn-sm" style="width: 100%;" type="button">关闭</button>
                </a>
            </div>
        </div>
    </form>

</div>

art/templates/ArtUpload.html
<div id="wall" style="width: 700px; height: 500px;">

    <div class="row" style="padding: 20px;">
        <div class="col-xs-8">
            <h3 style="margin: 0;">上传资源</h3>
        </div>
        <div class="col-xs-4" style="text-align: center;">
            <a href="javascript:closeDiv();">
                <div style="width: 26px; height: 26px; line-height: 28px; background: #337ab7; color: #ffffff; float: right;">
                    <span class="glyphicon glyphicon-remove"></span>
                </div>
            </a>
        </div>
    </div>

    <div style="width: 100%; height: 2px; background: #337ab7;"></div>

    {% for p in art_list %}
        <div class="artinfos" style="margin-top: 20px;">
            <div class="col-xs-6">
                <h4>任务描述</h4>
                <textarea class="form-control" style="height: 250px; resize: none;" disabled>{{ p.description }}</textarea>
            </div>
            <div class="col-xs-6">
                <h4>任务信息</h4>
                <div id="pic_info">
                    <div class="col-xs-5">类别</div>
                    <div class="col-xs-7">{{ p.group }}</div>
                </div>
                <div id="pic_info">
                    <div class="col-xs-5">上传文件类型</div>
                    <div class="col-xs-7">{{ p.format }}</div>
                </div>
                {% for q in p.art_info %}
                    <div id="pic_info">
                        <div class="col-xs-5">{{ q.name }}</div>
                        <div class="col-xs-7">{{ q.value }}</div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <form action="{% url 'art:resource_upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="uploads">
                <div class="col-xs-4">
                    <div class="form-group">
                        <label for="priority">资源截图</label>
                        <input type="file" class="form-control input-sm" name="preview">
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="form-group">
                        <label for="priority">资源原文件</label>
                        <input type="file" class="form-control input-sm" name="resource">
                    </div>
                </div>
                <div class="col-xs-2">
                    <button class="btn btn-primary btn-block btn-sm" style="width: 100%;">上传</button>
                </div>
                <div class="col-xs-2">
                    <input type="hidden" name="big_version" value="{{ p.big_version }}">
                    <input type="hidden" name="art_id" value="{{ art_id }}">
                    <a href="javascript:closeDiv();">
                        <button class="btn btn-primary btn-block btn-sm" style="width: 100%;" type="button">关闭</button>
                    </a>
                </div>
            </div>
        </form>
    {% endfor %}

</div>