ArtWorkManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
    url(r'^developer/', include('developer.urls', namespace='developer')),
    url(r'^art/', include('art.urls', namespace='art')),
    url(r'^plan/', include('plan.urls', namespace='plan')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

art/urls.py
from django.conf.urls import patterns, include, url
from art import views

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='art'),

    url(r'^audit/$', views.ArtAuditView.as_view(), name='audit'),

    url(r'^upload/$', views.UploadTaskView.as_view(), name='upload'),

    url(r'^up_upload/$', views.UpdateUploadTaskView.as_view(), name='up_upload'),

    url(r'^pass/$', views.ArtPassView.as_view(), name='pass'),

    url(r'^faild/$', views.ArtFaildView.as_view(), name='faild'),

    url(r'^resource_upload/$', views.upload, name='resource_upload'),

    url(r'^update/$', views.update, name='update'),

]

developer/urls.py
from django.conf.urls import patterns, include, url
from developer import views

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='developer'),

    url(r'^gtt/$', views.GTTView.as_view(), name='gtt'),

    url(r'^search/$', views.search_image, name='search'),

    url(r'^download/$', views.download, name='download'),

]

login/urls.py
from django.conf.urls import patterns, include, url
from login import views

urlpatterns = [
    # ex: /sign_in/
    url(r'^sign_in/$', views.sign_in, name='sign_in'),

    # ex: /sign_out/
    url(r'^sign_out/$', views.sign_out, name='sign_out'),

    # ex: /sign_success/
    url(r'^menu/$', views.MenuViews.as_view(), name='menu'),
]

developer/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

developer/views.py
#coding=utf8

from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from home.models import *
from django.views.decorators.csrf import csrf_exempt
from PIL import Image
from wsgiref.util import FileWrapper

import simplejson
import mimetypes


def is_sign_in(request):
    if not request.user.is_authenticated():
        return ('/?next=%s' % request.path)
    else:
        if request.user.has_perm('home.can_developer'):
            return
        else:
            return ('/login/menu')


class IndexView(generic.View):
    templates_file = 'DeveloperIndex.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        group_list = list(Group.objects.all())

        context = {
            'group_list': group_list
        }

        return render(request,
                      self.templates_file,
                      context)


class GTTView(generic.View):
    templates_file = 'DeveloperGroup.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        if 'group_id' in request.GET and request.GET['group_id']:
            group_id = request.GET['group_id']
        else:
            return HttpResponse('Group ID 错误或不存在!')

        groups = list(Group.objects.filter(id=int(group_id)))
        if not groups:
            return HttpResponse('Group 不存在 或 Group ID 错误!')

        gtts = list(GroupToTag.objects.filter(group=int(group_id)))
        if not gtts:
            gtts = []
            gtt_list = []
        else:
            gtt_list = []
            for p in gtts:
                tag_id = int(p.tag.id)
                taginfos = list(TagInfo.objects.filter(group=int(group_id), tag=tag_id))
                if taginfos:
                    tag_info = {'name': p.tag.name, 'info': p.info, 'info_list': taginfos}
                else:
                    tag_info = {}
                gtt_list.append(tag_info)


        context = {
            'group_id': group_id,
            'group_name': groups.pop().name,
            'gtts': gtts,
            'gtt_list': gtt_list,
        }

        return render(request,
                      self.templates_file,
                      context)


@csrf_exempt
def search_image(request):

    req = simplejson.loads(request.body)

    image_list = []
    for tag_name in req.keys():
        if tag_name == 'group':
            group_id = int(req[tag_name])
            id_by_group = []
            groups = list(Art.objects.filter(group=group_id, is_pass=1, is_audit=1))
            if groups:
                for p in groups:
                    id_by_group.append(p.id)
            else:
                id_by_group = []
            image_list.append(id_by_group)
        else:
            tag_id = int(req[tag_name])
            tag_name = list(TagInfo.objects.filter(id=tag_id))
            for p in tag_name:

                id_by_tag = []
                for q in list(ArtInfo.objects.filter(tag=p.tag.id, value=p.name)):
                    id_by_tag.append(q.art.id)

                if id_by_tag:
                    image_list.append(id_by_tag)
                else:
                    id_by_tag = []
                    image_list.append(id_by_tag)

    x = image_list.pop()
    for art_id in image_list:
        if x != art_id:
            y = []
            for m in x:
                if m in art_id:
                    y.append(m)
            x = y

    if x:

        art_list = []
        for p in x:
            for b in list(Art.objects.filter(id=p)):
                info_list = []
                for q in list(ArtInfo.objects.filter(art=int(p))):
                    import_info = {'name': q.tag.name, 'value': q.value}
                    info_list.append(import_info)

                # 计算图片显示比例
                img = Image.open(b.screen_shot)
                with img as im:
                    width, height = im.size
                if width > height:
                    scale = "100%"
                    if height > 300:
                        scale = "50%"
                else:
                    scale = "50%"

                art_info = {'art_id': b.id, 'user': b.user, 'group': b.group, 'time': b.upload_time, 'version': b.version, 'preview': b.screen_shot, 'scale': scale, 'info_list': info_list}
                art_list.append(art_info)

        def artid(a):
            return a['art_id']

        artinfo_list = sorted(art_list, key=artid, reverse=True)

    else:

        artinfo_list = []

    context = {
        'artinfo_list': artinfo_list,
    }
    
    return render(request, 'DeveloperImage.html', context)


def download(request):

    if 'group_id' in request.GET and request.GET['group_id']:
        group_id = request.GET['group_id']
    else:
        return HttpResponse("Group ID 错误或不存在!")

    if 'art_id' in request.GET and request.GET['art_id']:
        art_id = request.GET['art_id']
    else:
        return HttpResponse("Art ID 错误或不存在!")

    arts = list(Art.objects.filter(id=int(art_id)))
    if not arts:
        return HttpResponse("ArtID错误或不存在!")

    groups = list(Group.objects.filter(id=int(group_id)))
    if not groups:
        return HttpResponse("Group ID 错误或不存在!")

    orders = list(TagOrder.objects.filter(group=int(group_id)).order_by('sort'))

    # Data conversion
    def conversion(x):
        a = hex(int(x))
        b = a[2:]
        c = b.zfill(3)
        return c

    # Filename
    if orders:
        filename_list = []
        for p in orders:
            if p.code == 'group':
                f = conversion(groups.pop().code)
                filename_list.append(f)
            else:
                tags = list(Tag.objects.filter(name=p.code))
                if not tags:
                    return HttpResponse("Tag不存在!")

                art_info = list(ArtInfo.objects.filter(art=int(art_id), tag=int(tags.pop().id)))
                if art_info:
                    for p in art_info:
                        tag_code = list(TagInfo.objects.filter(tag=int(p.tag.id), name=p.value))
                        f = conversion(tag_code.pop().code)
                        filename_list.append(f)
                else:
                    f = conversion(0)
                    filename_list.append(f)
    else:
        filename_list = []
        f = conversion(groups.pop().code)
        filename_list.append(f)

        art_info = list(ArtInfo.objects.filter(art=int(art_id)))
        if not art_info:
            return HttpResponse("Art ID 错误或不存在!")

        for p in art_info:
            tag_code = list(TagInfo.objects.filter(tag=int(p.tag.id), name=p.value))
            f = conversion(tag_code.pop().code)
            filename_list.append(f)

    file_name = ""
    for q in filename_list:
        file_name += str(q)

    formats = list(Group.objects.filter(id=int(group_id)))
    if not formats:
        return HttpResponse("Group ID 错误或不存在!")

    filename = file_name + formats.pop().format

    # Download
    arts = list(Art.objects.filter(id=int(art_id)))
    if not arts:
        return HttpResponse("Art ID 错误或不存在!")

    for p in arts:

        url = p.resource_file.path
        wrapper = FileWrapper(open(url, 'rb'))
        content_type = mimetypes.guess_type(url)
        response = HttpResponse(wrapper, content_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename

        return response

developer/templates/DeveloperBase.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>ArtWorkManager | 搜索资源</title>
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'ArtWorkManager/css/main.css' %}" >
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'ArtWorkManager/js/main.js' %}"></script>
    <script src="{% static 'ArtWorkManager/js/jquery.poptrox.js' %}"></script>
</head>
<body>

    {% block content %}

    {% endblock %}

</body>
</html>

developer/templates/DeveloperGroup.html
{% if not gtts %}
    <h4>数据错误或不存在!</h4>
{% else %}
    {% for p in gtt_list %}
        {% if p %}
            <div class="form-group">
                <label for="{{ p.name }}">{{ p.info }} {{ p.name }}:</label>
                <select id="{{ p.name }}" onchange="search_image(this)" class="form-control input-sm" name="{{ group_name }}_{{ p.name }}">
                    <option value="">请选择</option>
                    {% for q in p.info_list  %}
                        <option value="{{ q.id }}">{{ q.name }}</option>
                    {% endfor %}
                </select>
            </div>
        {% else %}
            <h4>数据错误或不存在!</h4>
        {% endif %}
    {% endfor %}
{% endif %}

developer/templates/DeveloperImage.html
{% extends 'DeveloperBase.html' %}
{% block content %}

    <h2>搜索结果</h2>
    {% if artinfo_list %}
        {% for p in artinfo_list %}
            <div class="artinfo">
                <div class="row">
                    <div class="col-xs-7">
                        <h4 style="margin-left: 10px;">预览图<small>-点击图片可看大图</small></h4>
                        <div class="preview">
                            <script>
                                $(function() {
                                    $('#gallery{{ p.art_id }}').poptrox({
                                        usePopupCaption: true
                                    });
                                });
                            </script>
                            <div id="gallery{{ p.art_id }}" style="text-align: center;">
                                <a href="{{ MEDIA_URL }}{{ p.preview }}">
                                    <img width="{{ p.scale }}" src="{{ MEDIA_URL }}{{ p.preview }}"/>
                                </a>
                            </div>
                        </div>
                        <form action="{% url 'developer:download' %}" method="GET">
                            {% csrf_token %}
                            <input type="hidden" value="{{ p.art_id }}" name="art_id">
                            <input type="hidden" value="{{ p.group.id }}" name="group_id">
                            <button class="btn btn-sm btn-primary btn-block">资源下载</button>
                        </form>
                    </div>
                    <div class="col-xs-5">
                        <h4 class="row">资源信息</h4>
                        <div class="row" id="pic_info">
                            <div class="col-xs-5">类别</div>
                            <div class="col-xs-7">{{ p.group }}</div>
                        </div>
                        <div class="row" id="pic_info">
                            <div class="col-xs-5">作者</div>
                            <div class="col-xs-7">{{ p.user }}</div>
                        </div>
                        <div class="row" id="pic_info">
                            <div class="col-xs-5">版本</div>
                            <div class="col-xs-7">{{ p.version }}</div>
                        </div>
                        <div class="row" id="pic_info">
                            <div class="col-xs-5">上传时间</div>
                            <div class="col-xs-7" style="font-size: 10px;">{{ p.time }}</div>
                        </div>
                        {% for q in p.info_list %}
                            <div class="row" id="pic_info">
                                <div class="col-xs-5">{{ q.name }}</div>
                                <div class="col-xs-7">{{ q.value }}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>无结果!请更换搜索条件!</h3>
    {% endif %}

{% endblock %}

developer/templates/DeveloperIndex.html
{% extends 'DeveloperBase.html' %}
{% block content %}

    <div class="menus">
        <div class="row">
            <div class="col-xs-7">
                <a href="/login/menu/">
                    <h3>ArtWorkManager <small>美术资源管理系统</small></h3>
                </a>
            </div>
            <div class="col-xs-5">
                <h2 id="username">
                    <span class="glyphicon glyphicon-user"></span>{{ user.username }}　
                    <span class="glyphicon glyphicon-share-alt"></span>
                    <a href="{% url 'login:sign_out' %}">退出</a>
                </h2>
            </div>
        </div>
    </div>

    <div class="developer">
        <div class="row">
            <div class="col-xs-3">
                <a href="/login/menu/" style="color: #000000;"><h2>资源搜索</h2></a>
                {% if group_list %}
                    <div class="form-group">
                        <label for="group">类别</label>
                        <select name="group" id="group" class="form-control" onchange="search_gtt(this)">
                            <option value="">请选择</option>
                            {% for group in group_list %}
                                <option value="{{ group.id }}">{{ group.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div id="tag_info">
                        <h4>请选择资源类别</h4>
                    </div>
                {% else %}
                    <h4 style="text-align: center; font-size: 16px; margin-top: 40px;">请点击下方按钮添加类别</h4>
                    <a href="/manager/"><button type="button" class="btn btn-sm btn-primary btn-block" style="margin: auto; margin-bottom: 40px; width: 180px;">添加类别</button></a>
                {% endif %}
                <div class="form-group" style="display: none;">
                    <textarea id="images" class="form-control">{}</textarea>
                </div>
                <a href="/login/menu"><div id="back">返回主页</div></a>
            </div>
            <div class="col-xs-9">
                <div id="search_img">
                    <h2>搜索结果</h2>
                    <h3>请选择资源搜索条件!</h3>
                </div>
            </div>
        </div>
    </div>

{% endblock %}