ArtWorkManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
    url(r'^developer/', include('developer.urls', namespace='developer')),
    url(r'^art/', include('art.urls', namespace='art')),
    url(r'^plan/', include('plan.urls', namespace='plan')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

art/urls.py
from django.conf.urls import patterns, include, url
from art import views

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='art'),

    url(r'^audit/$', views.ArtAuditView.as_view(), name='audit'),

    url(r'^upload/$', views.UploadTaskView.as_view(), name='upload'),

    url(r'^up_upload/$', views.UpdateUploadTaskView.as_view(), name='up_upload'),

    url(r'^pass/$', views.ArtPassView.as_view(), name='pass'),

    url(r'^faild/$', views.ArtFaildView.as_view(), name='faild'),

    url(r'^resource_upload/$', views.upload, name='resource_upload'),

    url(r'^update/$', views.update, name='update'),

]

login/urls.py
from django.conf.urls import patterns, include, url
from login import views

urlpatterns = [
    # ex: /sign_in/
    url(r'^sign_in/$', views.sign_in, name='sign_in'),

    # ex: /sign_out/
    url(r'^sign_out/$', views.sign_out, name='sign_out'),

    # ex: /sign_success/
    url(r'^menu/$', views.MenuViews.as_view(), name='menu'),
]

manager/urls.py
from django.conf.urls import patterns, include, url
from manager import views

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='administrator'),

    url(r'^tag', views.TagView.as_view(), name='tag'),

    url(r'^updatetag/(?P<tag_id>\d+)', views.TagUpdateView.as_view(), name='updatetag'),

    url(r'^updategroup/(?P<group_id>\d+)', views.GroupUpdateView.as_view(), name='updategroup'),

    url(r'^updategtt/(?P<gtt_id>\d+)', views.GTTUpdateView.as_view(), name='updategtt'),

    url(r'^updateinfo/(?P<gtt_id>\d+)/(?P<info_id>\d+)', views.TagInfoUpdateView.as_view(), name='updateinfo'),

    # ADD

    url(r'^add', views.create, name='add'),

    url(r'^gttadd', views.create_gtt, name='gttadd'),

    url(r'^infoadd', views.create_taginfo, name='infoadd'),

    # update

    url(r'^update', views.update, name='update'),

    url(r'^infoupdate', views.update_taginfo, name='infoupdate'),

    # delete

    url(r'^delete', views.delete, name='delete'),

    url(r'^gtdelete', views.del_gtt, name='gtdelete'),

    url(r'^infodelete', views.del_taginfo, name='infodelete'),

]

manager/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

manager/views.py
#coding=utf8

from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from home.models import *


def is_sign_in(request):
    if not request.user.is_authenticated():
        return ('/?next=%s' % request.path)
    else:
        if request.user.has_perm('home.can_admin'):
            return
        else:
            return ('/login/menu')


class IndexView(generic.View):
    templates_file = 'Manager.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        groups = list(Group.objects.all().order_by('code'))
        if groups:
            group_list = []
            for p in groups:
                a = {'id': p.id, 'code': p.code, 'name': p.name, 'format': p.format}
                group_list.append(a)
        else:
            group_list = []

        formats = list(GroupFormat.objects.all())
        if not formats:
            formats = []

        if 'error' in request.GET and request.GET['error']:
            error_code = request.GET['error']
        else:
            error_code = ''

        if error_code == '1':
            error_txt = '添加失败!编号不能为空,不能重复,只能是数字!'
        elif error_code == '2':
            error_txt = '添加失败!名称不能为空!'
        elif error_code == '3':
            error_txt = '添加失败!文件类型不能为空或该类型不存在!'
        else:
            error_txt = ''

        context = {
            'group_list': sorted(group_list, key=lambda x: x['code']),
            'error_txt': error_txt,
            'formats': formats,
        }

        return render(request,
                      self.templates_file,
                      context)


class TagView(generic.View):
    templates_file = 'ManagerTag.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        tag_list = list(Tag.objects.all().order_by("code"))
        if not tag_list:
            tag_list = []

        if 'error' in request.GET and request.GET['error']:
            error_code = request.GET['error']
        else:
            error_code = ''

        if error_code == '1':
            error_txt = '添加失败!编号不能为空,不能重复,只能是数字!'
        elif error_code == '2':
            error_txt = '添加失败!名称不能为空!'
        else:
            error_txt = ''

        context = {
            'tag_list': tag_list,
            'error_txt': error_txt
        }

        return render(request,
                      self.templates_file,
                      context)


class TagUpdateView(generic.View):
    templates_file = 'TagUpdate.html'

    def get(self, request, tag_id):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        tags = list(Tag.objects.filter(id=int(tag_id)))
        if not tags:
            return HttpResponseRedirect('/manager/tag')

        if 'error' in request.GET and request.GET['error']:
            error_code = request.GET['error']
        else:
            error_code = ''

        if error_code == '1':
            error_txt = '更新失败!编号不能为空,不能重复,只能是数字!'
        elif error_code == '2':
            error_txt = '更新失败!名称不能为空!'
        elif error_code == '3':
            error_txt = '更新失败!Tag ID错误或不存在!'
        else:
            error_txt = ''

        context = {
            'tags': tags,
            'error_txt': error_txt
        }

        return render(request,
                      self.templates_file,
                      context)


class GroupUpdateView(generic.View):
    templates_file = 'GroupUpdate.html'

    def get(self, request, group_id):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        groups = list(Group.objects.filter(id=int(group_id)))
        if not groups:
            return HttpResponseRedirect('/manager')

        tags = list(Tag.objects.all())

        gtt_list = list(GroupToTag.objects.filter(group=int(group_id)))
        if not gtt_list:
            gtt_list = []

        formats = list(GroupFormat.objects.all())
        if not formats:
            formats = []

        if 'error' in request.GET and request.GET['error']:
            error_code = request.GET['error']
        else:
            error_code = ''

        if error_code == '1':
            error_txt = '更新失败!编号不能为空,不能重复,只能是数字!'
        elif error_code == '2':
            error_txt = '更新失败!名称不能为空!'
        elif error_code == '3':
            error_txt = '更新失败!文件类型不能为空或该类型不存在!'
        elif error_code == '4':
            error_txt = '更新失败!Group ID错误或不存在!'
        else:
            error_txt = ''

        context = {
            'groups': groups,
            'tags': tags,
            'gtt_list': gtt_list,
            'group_id': group_id,
            'error_txt': error_txt,
            'formats': formats
        }

        return render(request,
                      self.templates_file,
                      context)


class GTTUpdateView(generic.View):
    templates_file = 'GTTUpdate.html'

    def get(self, request, gtt_id):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        gtts = list(GroupToTag.objects.filter(id=int(gtt_id)))
        if not gtts:
            gtts = []

        taginfo_list = []
        for p in gtts:
            taginfos = list(TagInfo.objects.filter(group=int(p.group.id), tag=(p.tag.id)))
            if taginfos:
                taginfo_list = taginfos
            else:
                taginfo_list = []

        if 'error' in request.GET and request.GET['error']:
            error_code = request.GET['error']
        else:
            error_code = ''

        if error_code == '1':
            error_txt = '添加失败!编号不能为空,不能重复,只能是数字!'
        elif error_code == '2':
            error_txt = '添加失败!名称不能为空!'
        elif error_code == '3':
            error_txt = '添加失败!Group ID错误或不存在!'
        elif error_code == '4':
            error_txt = '添加失败!Tag ID错误或不存在!'
        elif error_code == '0':
            error_txt = '更新失败!标签信息错误,不存在或GTT ID错误,不存在!'
        else:
            error_txt = ''

        context = {
            'gtts': gtts,
            'gtt_id': gtt_id,
            'error_txt': error_txt,
            'error_code': error_code,
            'taginfo_list': taginfo_list
        }

        return render(request,
                      self.templates_file,
                      context)


class TagInfoUpdateView(generic.View):
    templates_file = 'TagInfoUpdate.html'

    def get(self, request, gtt_id, info_id):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        taginfos = list(TagInfo.objects.filter(id=int(info_id)))
        if taginfos:
            taginfo_list = taginfos
        else:
            taginfo_list = []

        if 'error' in request.GET and request.GET['error']:
            error_code = request.GET['error']
        else:
            error_code = '0'

        if error_code == '1':
            error_txt = '更新失败!编号不能为空,不能重复,只能是数字!'
        elif error_code == '2':
            error_txt = '更新失败!名称不能为空!'
        elif error_code == '3':
            error_txt = '更新失败!TagInfo ID错误或不存在!'
        else:
            error_txt = ''

        context = {
            'gtt_id': gtt_id,
            'error_txt': error_txt,
            'taginfo_list': taginfo_list
        }

        return render(request,
                      self.templates_file,
                      context)


# ADD


def create(request):

    if 'GInfo' in request.POST and request.POST['GInfo']:
        info_name = request.POST['GInfo']
    else:
        return HttpResponse("GInfo参数不存在!")

    # Group
    def group():

        # Code
        if 'code' in request.POST and request.POST['code']:
            code = request.POST['code']
        else:
            return ('/manager/?error=1')

        # Name
        if 'name' in request.POST and request.POST['name']:
            name = request.POST['name']
        else:
            return ('/manager/?error=2')

        # Format
        if 'format' in request.POST and request.POST['format']:
            format = request.POST['format']
        else:
            return ("/manager/?error=3")

        group_code = int(code)
        group_name = name

        add_group = Group(code=group_code,
                          name=group_name,
                          format=format)
        add_group.save()

        return ('/manager/')

    # Tag
    def tag():

        # Code
        if 'code' in request.POST and request.POST['code']:
            code = request.POST['code']
        else:
            return ('/manager/tag/?error=1')

        # Name
        if 'name' in request.POST and request.POST['name']:
            name = request.POST['name']
        else:
            return ('/manager/tag/?error=2')

        tag_code = int(code)
        tag_name = name

        add_tag = Tag(code=tag_code,
                      name=tag_name)
        add_tag.save()

        return ('/manager/tag/')

    add = {
        "group": group,
        "tag": tag,
    }

    http = add[info_name]()
    return HttpResponseRedirect(http)


# ADD GroupToTag
def create_gtt(request):

    if 'group_id' in request.POST and request.POST['group_id']:
        group_id = request.POST['group_id']
    else:
        return HttpResponse('Group ID不能为空!')

    groups = list(Group.objects.filter(id=int(group_id))).pop()

    tagid_list = list(request.POST.getlist('tag_list'))

    if not tagid_list:
        return HttpResponse('Tag ID不能为空!')

    for p in tagid_list:
        tags = list(Tag.objects.filter(id=int(p)))
        if tags:
            tag = tags.pop()
        else:
            return HttpResponse('Tag不存在!')

        if ('info_' + p) in request.POST and request.POST['info_' + p]:
            infos = request.POST['info_' + p]
        else:

manager/templates/GTTUpdate.html
{% extends 'ManagerBase.html' %}
{% block content %}

    <h2>类别管理 Group</h2>
    {% for p in gtts %}
        <table class="table">
            <thead style="font-size: 20px; font-weight: 800; text-align: left;">
                <tr>
                    <td colspan="2" style="vertical-align: middle;">更新类别标签</td>
                    <td align="right">
                        <form method="get" action="{% url 'manager:gtdelete' %}">
                            {% csrf_token %}
                            <input type="hidden" name="group_id" value="{{ p.group.id }}">
                            <input type="hidden" name="gtt_id" value="{{ p.id }}">
                            <button class="btn btn-primary btn-block btn-sm" style="width: 50px;">删除</button>
                        </form>
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="vertical-align: middle;"><strong>类别 Group</strong></td>
                    <td colspan="2">
                        {{ p.group.name }}
                    </td>
                </tr>
                <tr>
                    <td style="vertical-align: middle;"><strong>标签 Tag</strong></td>
                    <td  style="width: 80%;" colspan="2">
                        {{ p.tag.name }}
                    </td>
                </tr>
                <form action="{% url 'manager:update' %}" method="post">
                    {% csrf_token %}
                    <tr>
                        <td style="vertical-align: middle;"><strong>标签信息 Info</strong></td>
                        <td  style="width: 80%;" colspan="2">
                            <input type="text" class="form-control input-sm" style="width: 300px;" name="info" value="{{ p.info }}">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/manager/updategroup/{{ p.group.id }}"><button class="btn btn-primary btn-block btn-sm" type="button" style="width: 50px;">返回</button></a>
                        </td>
                        <td align="right" colspan="2">
                            <button class="btn btn-primary btn-block btn-sm" type="submit" style="width: 50px;">保存</button>
                            <input type="hidden" name="GInfo" value="gtt">
                            <input type="hidden" name="GID" value="{{ p.id }}">
                        </td>
                    </tr>
                </form>
            </tbody>
        </table>

        {% if error_txt and error_code == '0' %}
            <script>
                function error_hide(){
                    $("#error_txt").fadeOut("5000");
                }
                $(function() {
                    $("#error_txt").slideDown("slow");
                    setTimeout('error_hide()',5000);
                });
            </script>
            <div id="error_txt" class="alert alert-danger" role="alert" style="text-align: center; display: none;">{{ error_txt }}</div>
        {% endif %}

        <form method="post" action="{% url 'manager:infoadd' %}">
            {% csrf_token %}
            <table class="table" style="text-align: center;">
                <thead style="font-size: 14px; font-weight: 800;">
                    <tr style="font-size: 14px; text-align: left; background: #337ab7; color: #ffffff">
                        <td colspan="5">标签信息 TagInfo</td>
                    </tr>
                    <tr>
                        <td colspan="5" align="left">添加标签信息</td>
                    </tr>
                </thead>
                <tbody>
                    <td style="vertical-align: middle;"><strong>Code</strong></td>
                    <td>
                        <input type="text" class="form-control input-sm" name="code" placeholder="编号">
                    </td>
                    <td style="vertical-align: middle;"><strong>Name</strong></td>
                    <td>
                        <input type="text" class="form-control input-sm" name="name" placeholder="名称">
                    </td>
                    <td>
                        <button id="add" class="btn btn-primary btn-block btn-sm" type="submit" style="width: 100%;">添加</button>
                        <input type="hidden" name="GInfo" value="taginfo">
                        <input type="hidden" name="group_id" value="{{ p.group.id }}">
                        <input type="hidden" name="tag_id" value="{{ p.tag.id }}">
                        <input type="hidden" name="gtt_id" value="{{ gtt_id }}">
                    </td>
                </tbody>
            </table>
        </form>
    {% endfor %}

    {% if error_txt and error_code != '0' %}
        <script>
            function error_hide(){
                $("#error_txt").fadeOut("5000");
            }
            $(function() {
                $("#error_txt").slideDown("slow");
                setTimeout('error_hide()',5000);
            });
        </script>
        <div id="error_txt" class="alert alert-danger" role="alert" style="text-align: center; display: none;">{{ error_txt }}</div>
    {% endif %}

    <table class="table" style="text-align: center;">
        <thead style="font-size: 14px; font-weight: 800;">
            <tr>
                <td colspan="3" align="left">标签信息列表</td>
            </tr>
            <tr>
                <td>编号 Code</td>
                <td>名称 Name</td>
                <td>操作 Operation</td>
            </tr>
        </thead>
        <tbody>
        {% if not taginfo_list %}
            <tr>
                <td colspan="3">没有标签信息,请添加!</td>
            </tr>
        {% else %}
            {% for p in taginfo_list %}
                <tr>
                    <td style="vertical-align: middle;">{{ p.code }}</td>
                    <td style="vertical-align: middle;">{{ p.name }}</td>
                    <td style="vertical-align: middle;">
                        <a href="/manager/updateinfo/{{ gtt_id }}/{{ p.id }}"><button class="btn btn-primary btn-block btn-sm" style="width: 100%;">更新</button></a>
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>


{% endblock %}

manager/templates/GroupUpdate.html
{% extends 'ManagerBase.html' %}
{% block content %}

    <h2>类别管理 Group</h2>
    <table class="table">
        {% for p in groups %}
            <thead style="font-size: 20px; font-weight: 800; text-align: left;">
                <tr>
                    <td style="vertical-align: middle;">更新类别</td>
                    <td colspan="2" align="right">
                        <form method="get" action="{% url 'manager:delete' %}">
                            {% csrf_token %}
                            <input type="hidden" name="GInfo" value="group">
                            <input type="hidden" name="GID" value="{{ p.id }}">
                            <button class="btn btn-primary btn-block btn-sm" style="width: 50px;">删除</button>
                        </form>
                    </td>
                </tr>
            </thead>
            <form method="post" action="{% url 'manager:update' %}">
                {% csrf_token %}
                <tbody>
                    <tr>
                        <td style="vertical-align: middle;"><strong>编号 Code</strong></td>
                        <td colspan="2">
                            <input type="text" class="form-control input-sm" style="width: 100px;" name="code" value="{{ p.code }}">
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle;"><strong>名称 Name</strong></td>
                        <td  style="width: 80%;" colspan="2">
                            <input type="text" class="form-control input-sm" style="width: 300px;" name="name" value="{{ p.name }}">
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle;"><strong>文件类型 Format</strong></td>
                        <td  style="width: 80%;" colspan="2">
                            <select name="format" style="width: 300px;" class="form-control input-sm">
                                {% for q in formats %}
                                    <option value="{{ q.name }}" {% if p.format == q.name %}selected{% endif %}>{{ q.name }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/manager"><button class="btn btn-primary btn-block btn-sm" type="button" style="width: 50px;">返回</button></a>
                        </td>
                        <td align="right" colspan="2">
                            <button class="btn btn-primary btn-block btn-sm" type="submit" style="width: 50px;">保存</button>
                            <input type="hidden" name="GInfo" value="group">
                            <input type="hidden" name="GID" value="{{ p.id }}">
                        </td>
                    </tr>
                </tbody>
            </form>
        {% endfor %}
    </table>

    {% if error_txt %}
        <script>
            function error_hide(){
                $("#error_txt").fadeOut("5000");
            }
            $(function() {
                $("#error_txt").slideDown("slow");
                setTimeout('error_hide()',5000);
            });
        </script>
        <div id="error_txt" class="alert alert-danger" role="alert" style="text-align: center; display: none;">{{ error_txt }}</div>
    {% endif %}

    <div class="row">
        <div class="col-xs-5">
            <form method="post" action="{% url 'manager:gttadd' %}">
                {% csrf_token %}
                <table class="table" style="text-align: center;">
                    <thead style="font-size: 14px; font-weight: 800;">
                        <tr style="font-size: 14px; text-align: left; background: #337ab7; color: #ffffff">
                            <td colspan="3">添加GGT</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>标签</td>
                            <td>标签信息</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% if tags %}
                            {% for p in tags %}
                                <tr>
                                    <td style="vertical-align: middle;">
                                        <input type="checkbox" name="tag_list" value="{{ p.id }}">
                                    </td>
                                    <td style="vertical-align: middle;">
                                        {{ p.name }}
                                    </td>
                                    <td style="vertical-align: middle;">
                                        <input type="text" class="form-control input-sm" name="info_{{ p.id }}" placeholder="标签信息">
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="3">
                                    <button id="add" class="btn btn-primary btn-block btn-sm" type="submit" style="width: 100%;">添加</button>
                                    <input type="hidden" name="group_id" value="{{ group_id }}">
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="3">没有标签,请添加标签!</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </form>
        </div>
        <div class="col-xs-7">
            <table class="table" style="text-align: center;">
                <thead style="font-size: 14px; font-weight: 800;">
                    <tr style="font-size: 14px; text-align: left; background: #337ab7; color: #ffffff">
                        <td colspan="3">类别所属标签 Group To Tag</td>
                    </tr>
                    <tr>
                        <td>标签 Tag</td>
                        <td>标签信息 Info</td>
                        <td>操作 Operation</td>
                    </tr>
                </thead>
                <tbody>
                {% if not gtt_list %}
                    <tr>
                        <td colspan="3">没有类别所属标签,请添加!</td>
                    </tr>
                {% else %}
                    {% for p in gtt_list %}
                    <tr>
                        <td style="vertical-align: middle;">{{ p.tag.name }}</td>
                        <td style="vertical-align: middle;">{{ p.info }}</td>
                        <td style="vertical-align: middle;">
                            <a href="/manager/updategtt/{{ p.id }}"><button class="btn btn-primary btn-block btn-sm" style="width: 100%;">管理TagInfo</button></a>
                        </td>
                    </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

manager/templates/ManagerBase.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>ArtWorkManager | 后台管理</title>
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'ArtWorkManager/css/main.css' %}" >
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="menus">
        <div class="row">
            <div class="col-xs-7">
                <a href="/login/menu/">
                    <h3>ArtWorkManager <small>美术资源管理系统</small></h3>
                </a>
            </div>
            <div class="col-xs-5">
                <h2 id="username">
                    <span class="glyphicon glyphicon-user"></span>{{ user.username }}　
                    <span class="glyphicon glyphicon-share-alt"></span>
                    <a href="{% url 'login:sign_out' %}">退出</a>
                </h2>
            </div>
        </div>
    </div>

    <div class="manager">
        <div class="row">
            <div class="col-xs-3">
                <a href="/login/menu/" style="color: #000000;"><h2>后台管理</h2></a>
                <ul>
                    <li><a href="/manager/">类别管理 Group</a></li>
                    <li><a href="/manager/tag/">标签管理 Tag</a></li>
                    <li><a href="/admin/auth/user/">用户管理 User</a></li>
                </ul>
                <a href="/login/menu"><div id="back">返回主页</div></a>
            </div>
            <div class="col-xs-9">
                <div class="manager-panel">

                    {% block content %}

                    {% endblock %}

                </div>
            </div>
        </div>
    </div>

</body>
</html>

manager/templates/TagInfoUpdate.html
{% extends 'ManagerBase.html' %}
{% block content %}

    <h2>类别管理 Group</h2>
    <table class="table">
        {% for p in taginfo_list %}
            <thead style="font-size: 20px; font-weight: 800; text-align: left;">
                <tr>
                    <td style="vertical-align: middle;">更新标签信息</td>
                    <td colspan="2" align="right">
                        <form method="get" action="{% url 'manager:infodelete' %}">
                            {% csrf_token %}
                            <input type="hidden" name="gtt_id" value="{{ gtt_id }}">
                            <input type="hidden" name="info_id" value="{{ p.id }}">
                            <button class="btn btn-primary btn-block btn-sm" style="width: 50px;">删除</button>
                        </form>
                    </td>
                </tr>
            </thead>
            <form method="post" action="{% url 'manager:infoupdate' %}">
                {% csrf_token %}
                <tbody>
                    <tr>
                        <td style="vertical-align: middle;"><strong>类别 Group</strong></td>
                        <td colspan="2">
                            {{ p.group.name }}
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle;"><strong>标签 Tag</strong></td>
                        <td  style="width: 80%;" colspan="2">
                            {{ p.tag.name }}
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle;"><strong>编号 Code</strong></td>
                        <td colspan="2">
                            <input type="text" class="form-control input-sm" style="width: 100px;" name="code" value="{{ p.code }}">
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle;"><strong>名称 Name</strong></td>
                        <td  style="width: 80%;" colspan="2">
                            <input type="text" class="form-control input-sm" style="width: 300px;" name="name" value="{{ p.name }}">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/manager/updategtt/{{ gtt_id }}"><button class="btn btn-primary btn-block btn-sm" type="button" style="width: 50px;">返回</button></a>
                        </td>
                        <td align="right" colspan="2">
                            <button class="btn btn-primary btn-block btn-sm" type="submit" style="width: 50px;">保存</button>
                            <input type="hidden" name="gtt_id" value="{{ gtt_id }}">
                            <input type="hidden" name="info_id" value="{{ p.id }}">
                        </td>
                    </tr>
                </tbody>
            </form>
        {% endfor %}
    </table>

    {% if error_txt %}
        <script>
            function error_hide(){
                $("#error_txt").fadeOut("5000");
            }
            $(function() {
                $("#error_txt").slideDown("slow");
                setTimeout('error_hide()',5000);
            });
        </script>
        <div id="error_txt" class="alert alert-danger" role="alert" style="text-align: center; display: none;">{{ error_txt }}</div>
    {% endif %}

{% endblock %}