ArtWorkManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
    url(r'^developer/', include('developer.urls', namespace='developer')),
    url(r'^art/', include('art.urls', namespace='art')),
    url(r'^plan/', include('plan.urls', namespace='plan')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

art/urls.py
from django.conf.urls import patterns, include, url
from art import views

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='art'),

    url(r'^audit/$', views.ArtAuditView.as_view(), name='audit'),

    url(r'^upload/$', views.UploadTaskView.as_view(), name='upload'),

    url(r'^up_upload/$', views.UpdateUploadTaskView.as_view(), name='up_upload'),

    url(r'^pass/$', views.ArtPassView.as_view(), name='pass'),

    url(r'^faild/$', views.ArtFaildView.as_view(), name='faild'),

    url(r'^resource_upload/$', views.upload, name='resource_upload'),

    url(r'^update/$', views.update, name='update'),

]

login/urls.py
from django.conf.urls import patterns, include, url
from login import views

urlpatterns = [
    # ex: /sign_in/
    url(r'^sign_in/$', views.sign_in, name='sign_in'),

    # ex: /sign_out/
    url(r'^sign_out/$', views.sign_out, name='sign_out'),

    # ex: /sign_success/
    url(r'^menu/$', views.MenuViews.as_view(), name='menu'),
]

plan/urls.py
from django.conf.urls import patterns, include, url
from plan import views

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='plan'),

    url(r'^gtt/$', views.GTTView.as_view(), name='gtt'),

    url(r'^search_bv/$', views.search_bv, name='search_bv'),

    url(r'^admin_plan/$', views.PlanAdminView.as_view(), name='admin_plan'),

    url(r'^audit_plan/$', views.PlanAuditView.as_view(), name='audit_plan'),

    url(r'^pass_task/$', views.PassTaskView.as_view(), name='pass_task'),

    url(r'^faild_task/$', views.FaildTaskView.as_view(), name='faild_task'),

    url(r'^task_audit/(?P<art_id>\d+)/$', views.AuditTaskView.as_view(), name='task_audit'),

    url(r'^tag_order/$', views.PlanOrderView.as_view(), name='tag_order'),

    url(r'^order/$', views.order, name='order'),

    url(r'^sort/$', views.sort, name='sort'),

    url(r'^create_task/$', views.create_task, name='create_task'),

    url(r'^del_task/$', views.del_task, name='del_task'),

    url(r'^download/$', views.download, name='download'),

    url(r'^audit/$', views.audit, name='audit'),

]

plan/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

plan/views.py
#coding=utf8

from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from home.models import *
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from wsgiref.util import FileWrapper
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import simplejson
import re
import time
import mimetypes


def is_sign_in(request):
    if not request.user.is_authenticated():
        return ('/?next=%s' % request.path)
    else:
        if request.user.has_perm('home.can_plan'):
            return
        else:
            return ('/login/menu')


def pagination(request, number, target):

    paginator = Paginator(target, number)
    page = request.GET.get('page')
    try:
        target = paginator.page(page)
    except PageNotAnInteger:
        target = paginator.page(1)
    except EmptyPage:
        target = paginator.page(paginator.num_pages)

    return (target)


class IndexView(generic.View):
    templates_file = 'PlanIndex.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        group_list = list(Group.objects.all())

        users = list(User.objects.all())
        user_list = []
        for p in users:
            if p.has_perm('home.can_art'):
                a = {'id': p.id, 'username': p.username}
                user_list.append(a)

        context = {
            'group_list': group_list,
            'user_list': user_list,
        }

        return render(request,
                      self.templates_file,
                      context)


class GTTView(generic.View):
    templates_file = 'ajax/PlanGroup.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        if 'group_id' in request.GET and request.GET['group_id']:
            group_id = request.GET['group_id']
        else:
            return HttpResponse('Group ID 错误或不存在!')

        groups = list(Group.objects.filter(id=int(group_id)))
        if not groups:
            return HttpResponse('Group 不存在 或 Group ID 错误!')

        gtts = list(GroupToTag.objects.filter(group=int(group_id)))
        if not gtts:
            gtts = []
            gtt_list = []
        else:
            gtt_list = []
            for p in gtts:
                tag_id = int(p.tag.id)
                taginfos = list(TagInfo.objects.filter(group=int(group_id), tag=tag_id))
                if taginfos:
                    tag_info = {'name': p.tag.name, 'info': p.info, 'info_list': taginfos}
                else:
                    tag_info = {}
                gtt_list.append(tag_info)


        context = {
            'group_id': group_id,
            'group_name': groups.pop().name,
            'gtts': gtts,
            'gtt_list': gtt_list,
        }

        return render(request,
                      self.templates_file,
                      context)


class PlanAdminView(generic.View):
    templates_file = 'PlanAdmin.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        # img null
        nart_list = list(Art.objects.filter(screen_shot="", resource_file=""))
        if nart_list:
            narts = pagination(request, 10, nart_list)
            nimg = len(nart_list)
        else:
            narts = []
            nimg = 0

        # img not null
        yarts = list(Art.objects.all())
        if yarts:
            yimg = len(yarts) - nimg
        else:
            yimg = 0

        context = {
            'narts': narts,
            'nimg': nimg,
            'yimg': yimg,
        }

        return render(request,
                      self.templates_file,
                      context)


def count(request):

    yarts = list(Art.objects.filter(screen_shot="", resource_file=""))
    if not yarts:
        yarts = []
    warts = list(Art.objects.filter(is_audit=0))
    if not warts:
        warts = []

    wsh_list = []
    for p in warts:
        if p not in yarts:
            wsh_list.append(p)

    if wsh_list:
        wsh = len(wsh_list)
        wshs = pagination(request, 10, wsh_list)
    else:
        wsh = 0
        wshs = []

    part_list = list(Art.objects.filter(is_audit=1, is_pass=1))
    if part_list:
        psh = len(part_list)
        parts = pagination(request, 10, part_list)
    else:
        psh = 0
        parts = []

    fart_list = list(Art.objects.filter(is_audit=1, is_pass=0))
    if fart_list:
        fsh = len(fart_list)
        farts = pagination(request, 10, fart_list)
    else:
        fsh = 0
        farts = []

    context = {
        'wsh': wsh,
        'psh': psh,
        'fsh': fsh,
        'wshs': wshs,
        'parts': parts,
        'farts': farts,
    }

    return context


class PlanAuditView(generic.View):
    templates_file = 'PlanAudit.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        context = count(request)

        return render(request,
                      self.templates_file,
                      context)


class AuditTaskView(generic.View):
    templates_file = 'AuditTask.html'

    def get(self, request, art_id):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        arts = list(Art.objects.filter(id=int(art_id)))
        if not arts:
            return HttpResponse("Art ID错误或不存在!")

        art_list = []
        for p in arts:
            artinfos = list(ArtInfo.objects.filter(id=p.id))
            if not artinfos:
                return HttpResponse("ArtInfo不存在!")
            a = {"id": p.id,
                 "group": p.group,
                 "version": p.version,
                 "preview": p.screen_shot,
                 "resource": p.resource_file,
                 "decription": p.description,
                 "artinfo": artinfos,
                 "user": p.user.username,}
            art_list.append(a)

        context = {
            "art_id": art_id,
            "art_list": art_list,
        }

        return render(request,
                      self.templates_file,
                      context)


class PassTaskView(generic.View):
    templates_file = 'PassTask.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        context = count(request)

        return render(request,
                      self.templates_file,
                      context)


class FaildTaskView(generic.View):
    templates_file = 'FaildTask.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        context = count(request)

        return render(request,
                      self.templates_file,
                      context)


class PlanOrderView(generic.View):
    templates_file = 'PlanOrder.html'

    def get(self, request):

        is_log_in = is_sign_in(request)
        if is_log_in:
            return HttpResponseRedirect(is_log_in)

        groups = list(Group.objects.all())
        if not groups:
            groups = []

        context = {
            'groups': groups
        }

        return render(request,
                      self.templates_file,
                      context)


@csrf_exempt
def search_bv(request):

    req = simplejson.loads(request.body)

    version_list = []
    for tag_name in req.keys():
        if tag_name == 'group':
            group_id = int(req[tag_name])
            version_by_group = []
            for p in list(Art.objects.filter(group=group_id)):
                version_by_group.append(p.version)
            version_list.append(version_by_group)
        else:
            tag_id = int(req[tag_name])
            tag_name = list(TagInfo.objects.filter(id=tag_id)).pop()
            version_by_tag = []
            for q in list(ArtInfo.objects.filter(tag=tag_id, value=tag_name.name)):
                version_by_tag.append(q.art.version)
            if version_by_tag:
                version_list.append(version_by_tag)

    x = version_list.pop()
    for version_num in version_list:
        if x != version_num:
            y = []
            for m in x:
                if m in version_num:
                    y.append(m)
            x = y

    bv_info = []
    for p in x:
        it = re.finditer(r"\d+", p)
        num = []
        for match in it:
            b = match.group()
            num.append(b)
        bv_info.append(num[0])

    if bv_info:
        max_bv = int(max(bv_info)) + 1
        n = 1
        bv_list = []
        while n <= max_bv:
            bv_list.append(n)
            n = n + 1
    else:
        bv_list = [1]

    context = {
        'bv_list': bv_list,
    }

    return render(request, 'ajax/PlanVersion.html', context)


def create_task(request):

    if request.method == 'GET':
        return HttpResponse("request method error")

    if 'group' in request.POST and request.POST['group']:
        group_id = request.POST['group']
        groups = list(Group.objects.filter(id=int(group_id))).pop()
    else:
        return HttpResponse("error in group")

    if 'username' in request.POST and request.POST['username']:
        user_id = request.POST['username']
        users = list(User.objects.filter(id=int(user_id))).pop()
    else:
        return HttpResponse("error in username")

    if 'big_version' in request.POST and request.POST['big_version']:
        big_version = request.POST['big_version']
    else:
        return HttpResponse("error in big_version")

    if 'priority' in request.POST and request.POST['priority']:
        priority = request.POST['priority']

plan/templates/AuditTask.html
{% extends 'PlanBase.html' %}
{% block content %}

    <script>
        $(function() {
            $('#art{{ art_id }}').poptrox({
                usePopupCaption: true
            });
        });
    </script>
    <h2>审核任务</h2>
    {% for p in art_list %}
        <div class="row">
            <div class="col-xs-7">
                <form action="{% url 'plan:download' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{ art_id }}" name="art_id">
                    <div class="row">
                        <div class="col-xs-8">
                            <h3>预览图</h3>
                        </div>
                        <div class="col-xs-4" style="text-align: right;">
                            <button class="btn btn-sm btn-default" style="width: 60px; margin-top: 20px;">下载</button>
                        </div>
                    </div>
                </form>
                <div id="art{{ art_id }}" style="text-align: center;">
                    <a href="{{ MEDIA_URL }}{{ p.preview }}">
                        <img width="60%" src="{{ MEDIA_URL }}{{ p.preview }}" />
                    </a>
                </div>
                <form method="post" action="{% url 'plan:audit' %}">
                    {% csrf_token %}
                    <h3>审核意见</h3>
                    <label for="description">是否通过</label>
                    <div class="radio">
                        <label>
                            <input type="radio" value="1" name="is_pass">通过
                        </label>
                        <label style="margin-left: 20px">
                            <input type="radio" value="0" name="is_pass">未通过
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="description">修改意见</label>
                        <textarea class="form-control" name="reason" placeholder="任务通过审核,不需填写" style="height: 100px; resize: none;"></textarea>
                    </div>
                    <input type="hidden" value="{{ art_id }}" name="art_id">
                    <div class="row">
                        <div class="col-xs-4">
                            <button class="btn btn-sm btn-primary btn-block" style="width: 140px;">提交</button>
                        </div>
                        <div class="col-xs-8">
                            <a href="/plan/audit_plan/">
                                <button class="btn btn-sm btn-primary btn-block" style="width: 140px;" type="button">返回</button>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-xs-5">
                <h3 class="row">任务信息</h3>
                <div class="row">
                    <div class="col-xs-4" id="at1">提交用户</div>
                    <div class="col-xs-8" id="at2">{{ p.user }}</div>
                </div>
                <div class="row">
                    <div class="col-xs-4" id="at1">类别</div>
                    <div class="col-xs-8" id="at2">{{ p.group.name }}</div>
                </div>
                {% for q in p.artinfo  %}
                    <div class="row">
                        <div class="col-xs-4" id="at1">{{ q.tag.name }}</div>
                        <div class="col-xs-8" id="at2">{{ q.value }}</div>
                    </div>
                {% endfor %}
                <div class="row">
                    <div class="col-xs-4" id="at1">版本号</div>
                    <div class="col-xs-8" id="at2">{{ p.version }}</div>
                </div>
                <div class="row" id="at3">任务描述</div>
                <div class="row" id="at4">{{ p.decription }}</div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

plan/templates/FaildTask.html
{% extends 'PlanBase.html' %}
{% block content %}

    <h2>审核任务</h2>

    <div class="row" style="margin-top: 20px;">
        <div class="col-xs-4">
            <a href="/plan/audit_plan/">
                <div class="admin_task">
                    <div class="dsh"></div>
                    <div class="task_font">等待审核</div>
                    <div class="task_num">{{ wsh }}</div>
                </div>
            </a>
        </div>
        <div class="col-xs-4">
            <a href="/plan/pass_task/">
                <div class="admin_task">
                    <span class="glyphicon glyphicon-ok-circle" style="color: green; font-size: 30px;"></span>
                    <div class="task_font">审核通过</div>
                    <div class="task_num">{{ psh }}</div>
                </div>
            </a>
        </div>
        <div class="col-xs-4">
            <a href="/plan/faild_task/">
                <div class="admin_task">
                    <span class="glyphicon glyphicon-remove-circle" style="color: red; font-size: 30px;"></span>
                    <div class="task_font">审核未通过</div>
                    <div class="task_num">{{ fsh }}</div>
                </div>
            </a>
        </div>
    </div>

    <table class="table" id="audit" style="margin-top: 20px;">
        <thead style="font-size: 14px; font-weight: 800;">
            <tr style="font-size: 20px; text-align: left;">
                <td colspan="5">审核未通过任务</td>
            </tr>
            <tr>
                <td>ID</td>
                <td>类别</td>
                <td>预览图</td>
                <td>审核未通过原因</td>
            </tr>
        </thead>
        <tbody>
            {% if not farts %}
                <tr>
                    <td colspan="4">
                        <h4>没有审核未通过任务!</h4>
                    </td>
                </tr>
            {% else %}
                {% for p in farts %}
                    <tr>
                        <td>{{ p.id }}</td>
                        <td>{{ p.group.name }}</td>
                        <td>
                                <script>
                                    $(function() {
                                        $('#gallery{{ p.id }}').poptrox({
                                            usePopupCaption: true
                                        });
                                    });
                                </script>
                            <div id="gallery{{ p.id }}">
                                <a href="{{ MEDIA_URL }}{{ p.screen_shot }}">
                                    <img width="150px" src="{{ MEDIA_URL }}{{ p.screen_shot }}" />
                                </a>
                            </div>
                        </td>
                        <td>
                            <textarea class="form-control" disabled>{{ p.reason }}</textarea>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>

    {% if farts and farts.paginator.num_pages != 1 %}
        <nav style="text-align: center;">
            <ul class="pagination">
                <li>
                    <a href="/plan/faild_task/?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li>
                    {% if farts.has_previous %}
                        <a href="/plan/faild_task/?page={{ farts.previous_page_number }}" aria-label="Previous">上一页</a>
                    {% else %}
                        <a href="/plan/faild_task/?page={{ farts.number }}" aria-label="Previous">上一页</a>
                    {% endif %}
                </li>
                {% for p in farts.paginator.page_range %}
                    <li {% if farts.number == p %}class="active"{% endif %}><a href="/plan/faild_task/?page={{ p }}">{{ p }}</a></li>
                {% endfor %}
                <li>
                    {% if farts.has_next %}
                        <a href="/plan/faild_task/?page={{ farts.next_page_number }}" aria-label="Previous">下一页</a>
                    {% else %}
                        <a href="/plan/faild_task/?page={{ farts.number }}" aria-label="Previous">下一页</a>
                    {% endif %}
                </li>
                <li>
                    <a href="/plan/faild_task/?page={{ farts.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}

{% endblock %}

plan/templates/PlanAdmin.html
{% extends 'PlanBase.html' %}
{% block content %}

    <h2>管理任务</h2>

    <div class="row" style="margin-top: 20px;">
        <div class="col-xs-6">
            <a href="/plan/audit_plan/">
                <div class="admin_task">
                    <span class="glyphicon glyphicon-ok-circle" style="color: green; font-size: 30px;"></span>
                    <div class="task_font">已提交资源任务</div>
                    <div class="task_num">{{ yimg }}</div>
                </div>
            </a>
        </div>
        <div class="col-xs-6">
            <a href="/plan/admin_plan/">
                <div class="admin_task">
                    <span class="glyphicon glyphicon-remove-circle" style="color: red; font-size: 30px;"></span>
                    <div class="task_font">未提交资源任务</div>
                    <div class="task_num">{{ nimg }}</div>
                </div>
            </a>
        </div>
    </div>

    <table class="table" id="audit" style="margin-top: 20px;">
        <thead style="font-size: 14px; font-weight: 800;">
            <tr style="font-size: 20px; text-align: left;">
                <td colspan="5">未提交资源任务</td>
            </tr>
            <tr>
                <td>ID</td>
                <td>类别</td>
                <td>任务优先级</td>
                <td>任务描述</td>
                <td>修改</td>
            </tr>
        </thead>
        <tbody>
            {% if not narts %}
                <tr>
                    <td colspan="5">没有未提交资源任务!</td>
                </tr>
            {% else %}
                {% for p in narts %}
                    <tr>
                        <td>{{ p.id }}</td>
                        <td>{{ p.group.name }}</td>
                        <td>{{ p.priority }}</td>
                        <td>
                            <textarea class="form-control" disabled>{{ p.description }}</textarea>
                        </td>
                        <td>
                            <form action="{% url 'plan:del_task' %}" method="get">
                                {% csrf_token %}
                                <input type="hidden" value="{{ p.id }}" name="art_id">
                                <button class="btn btn-primary btn-block btn-sm" style="width: 100%;">删除</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>

    {% if narts and narts.paginator.num_pages != 1 %}
        <nav style="text-align: center;">
            <ul class="pagination">
                <li>
                    <a href="/plan/audit_admin/?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li>
                    {% if narts.has_previous %}
                        <a href="/plan/audit_admin/?page={{ narts.previous_page_number }}" aria-label="Previous">上一页</a>
                    {% else %}
                        <a href="/plan/audit_admin/?page={{ narts.number }}" aria-label="Previous">上一页</a>
                    {% endif %}
                </li>
                {% for p in narts.paginator.page_range %}
                    <li {% if narts.number == p %}class="active"{% endif %}><a href="/plan/audit_admin/?page={{ p }}">{{ p }}</a></li>
                {% endfor %}
                <li>
                    {% if narts.has_next %}
                        <a href="/plan/audit_admin/?page={{ narts.next_page_number }}" aria-label="Previous">下一页</a>
                    {% else %}
                        <a href="/plan/audit_admin/?page={{ narts.number }}" aria-label="Previous">下一页</a>
                    {% endif %}
                </li>
                <li>
                    <a href="/plan/audit_admin/?page={{ narts.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}

{% endblock %}

plan/templates/PlanBase.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>ArtWorkManager | 任务管理</title>
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'ArtWorkManager/css/main.css' %}" >
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="{% static 'ArtWorkManager/js/main.js' %}"></script>
    <script src="{% static 'ArtWorkManager/js/jquery.poptrox.js' %}"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
</head>

<body>

    <div class="menus">
        <div class="row">
            <div class="col-xs-7">
                <a href="/login/menu/">
                    <h3>ArtWorkManager <small>美术资源管理系统</small></h3>
                </a>
            </div>
            <div class="col-xs-5">
                <h2 id="username">
                    <span class="glyphicon glyphicon-user"></span>{{ user.username }}　
                    <span class="glyphicon glyphicon-share-alt"></span>
                    <a href="{% url 'login:sign_out' %}">退出</a>
                </h2>
            </div>
        </div>
    </div>

    <div class="plan">
        <div class="row">
            <div class="col-xs-3">
                <a href="/login/menu/" style="color: #000000;"><h2>任务管理</h2></a>
                <ul>
                    <li><a href="/plan/">发布任务</a></li>
                    <li><a href="/plan/tag_order/">标签排序</a></li>
                    <li><a href="/plan/admin_plan/">管理任务</a></li>
                    <li><a href="/plan/audit_plan/">审核任务</a></li>
                </ul>
                <a href="/login/menu"><div id="back">返回主页</div></a>
            </div>
            <div class="col-xs-9">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

plan/templates/PlanIndex.html
{% extends 'PlanBase.html' %}
{% block content %}

        <form action="{% url 'plan:create_task' %}" method="post">
            {% csrf_token %}
            <h2>发布任务</h2>
            <div class="row">
                <div class="col-xs-6">
                    {% if group_list %}
                        <div class="form-group">
                            <label for="group">类别</label>
                            <select name="group" id="group" class="form-control" onchange="search_tag(this)">
                                <option value="">请选择</option>
                                {% for group in group_list %}
                                    <option value="{{ group.id }}">{{ group.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div id="tag_info">
                            <h4>请选择资源类别</h4>
                        </div>
                    {% else %}
                        <a href="/manager/"><button type="button" class="btn btn-lg btn-primary btn-block">添加类别</button></a>
                    {% endif %}
                    <div class="form-group" style="display: none;">
                        <textarea id="tags" class="form-control">{}</textarea>
                    </div>
                </div>
                <div class="col-xs-6">
                    {% if group_list %}
                        <div class="form-group">
                            <label for="username">任务完成人 User</label>
                            <select id="usernames" class="form-control input-sm" name="username">
                                {% for q in user_list  %}
                                    <option value="{{ q.id }}">{{ q.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="priority">任务优先级 Priority</label>
                            <input type="number" min="0" value="0" class="form-control" id="priority" name="priority">
                        </div>
                        <div id="big_version">
                            <div class="form-group">
                                <label for="big_version">任务版本号 Big_Version</label>
                                <select name="big_version" class="form-control" disabled></select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="description">任务描述 Description</label>
                            <textarea class="form-control" name="description" id="description" placeholder="Description"></textarea>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block">发布</button>
                    {% else %}
                        <div class="no-group">请点击左侧按钮添加类别</div>
                    {% endif %}
                </div>
            </div>
        </form>

{% endblock %}

plan/templates/PlanOrder.html
{% extends 'PlanBase.html' %}
{% block content %}

    <h2>标签排序</h2>

    <h4>注: 此为字段顺序，用于确定图片名称</h4>

    <form action="{% url 'plan:sort' %}" method="post" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label" style="font-size: 16px;">选择类别</label>
            <div class="col-sm-10">
                <select onchange="Order(this.value)" class="form-control" style="width: 300px;">
                    <option value="">请选择</option>
                    {% for group in groups %}
                        <option value="{{ group.id }}">{{ group.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div id="orderlist">
            <h4>请选择类别!</h4>
        </div>
    </form>

{% endblock %}